---
env:
  - HADOLINT_VERSION=1.18.0
language: python
python:
  - "3.8"

services:
  - docker

install:
  # Install pipenv to manage dependencies
  - pip install pipenv

  # Install Python software used for testing
  - pipenv install --dev --system --deploy

  # Install gems
  - bundle install

script:
  - awesome_bot --request-delay 1 --skip-save-results --allow-dupe --white-list=localhost --files $(ls *.md | paste -sd "," -)

  - pytest --doctest-modules --pylint --cov-report=term-missing --cov=galaxy_exporter tests galaxy_exporter

  - mypy galaxy_exporter/galaxy_exporter.py

  - coverage report --fail-under=100

  - curl -L "https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64" -o hadolint
    && chmod 0750 hadolint
    && ./hadolint --ignore=DL3018 Dockerfile

after_success:
  - codecov
