language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -e ".[testing]"

script:
  - awesome_bot --request-delay 1 --skip-save-results --allow-dupe --white-list=localhost --files $(ls *.md | paste -sd "," -)

  - pytest --doctest-modules --pep8 --cov-report=term-missing --cov=galaxy_exporter tests galaxy_exporter

  - coverage report --fail-under=100

after_success:
  - coveralls
