language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -e ".[testing]"

script:
  - pytest --doctest-modules --cov-report=term-missing --cov=galaxy_exporter tests galaxy_exporter

  - coverage report --fail-under=100

  - py.test --pep8
